Update build-and-deploy-omod.yml

diff --git a/.github/workflows/build-and-deploy-omod.yml b/.github/workflows/build-and-deploy-omod.yml
--- a/.github/workflows/build-and-deploy-omod.yml
+++ b/.github/workflows/build-and-deploy-omod.yml
@@ -34,6 +34,29 @@ jobs:
       - name: Install dependencies and build .omod file
         run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --file pom.xml
 
+
+      # - name: Copy .omod file to remote server
+      #   env:
+      #     SSH_PRIVATE_KEY: ${{ secrets.PRVKEY }}
+      #     REMOTE_SERVER: ${{ secrets.REMOTESERVER }}
+      #     SSH_USERNAME: ${{ secrets.REMOTEUSERNAME }}
+      #   run: |
+      #     # Debug the REMOTE_SERVER to ensure it's correctly set accessible
+      #     echo "REMOTE_SERVER is: $REMOTE_SERVER"
+          
+      #     # Set up SSH key for authentication
+      #     mkdir -p ~/.ssh
+      #     echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
+      #     chmod 600 ~/.ssh/id_rsa
+      #     ssh-keyscan -H $REMOTE_SERVER >> ~/.ssh/known_hosts
+          
+      #     # Navigate to the omod directory and target folder
+      #     cd omod/target
+          
+      #     # Copy the .omod file to the correct remote directory
+      #     scp -q *.omod $SSH_USERNAME@$REMOTE_SERVER:/home/openmrs/deploy/openmrs/openmrs-data/modules/
+
+
       - name: Copy .omod file to remote server
         env:
           SSH_PRIVATE_KEY: ${{ secrets.PRVKEY }}
@@ -49,8 +72,16 @@ jobs:
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan -H $REMOTE_SERVER >> ~/.ssh/known_hosts
           
+          # Optional: Test SSH connection to ensure it's working
+          if ssh -i ~/.ssh/id_rsa -o BatchMode=yes -o StrictHostKeyChecking=no $SSH_USERNAME@$REMOTE_SERVER 'exit'; then
+            echo "SSH connection established successfully."
+          else
+            echo "Error: Unable to establish SSH connection."
+            exit 1
+          fi
+      
           # Navigate to the omod directory and target folder
-          cd omod/target
+          cd omod/target || exit
           
           # Copy the .omod file to the correct remote directory
-          scp -q *.omod $SSH_USERNAME@$REMOTE_SERVER:/home/openmrs/deploy/openmrs/openmrs-data/modules/
+          scp -o StrictHostKeyChecking=no -o ConnectTimeout=30 -v *.omod $SSH_USERNAME@$REMOTE_SERVER:/home/openmrs/deploy/openmrs/openmrs-data/modules/
